# Configuración para PostgreSQL
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/laboratorioBD
    username: postgres
    password: pos123
    driver-class-name: org.postgresql.Driver

# Configuración para MongoDB
spring:
  data:
    mongodb:
      database: muestraDB
      uri: mongodb://root:1234@localhost:27017/
      username: root
      password: 1234
# Configuración adicional
logging:
  level:
    root: DEBUG